### ISSUE TITLE
recreate mpv rubberband profile command [question]

### ISSUE THREAD

**Issue by geextahslex** [breakfastquay/rubberband#105]
Hi, this is a question I didn't find any forum or something so I just ask here
I want to slow down a song to 95% with rubberband-r3 to make it exactly the same like the implementation in mpv. I tried to look into the help but I was overwhelmed by all the options. If someone could help me with this command line this would be awesome.

command:
`rubberband-r3 song.wav output.wav`

Thanks for any help :)

 tempo=0.95
 transients=mixed
 detector=compound
 phase=laminar
 window=standard
 smoothing=off
 formant=preserved
 pitch=consistency
 channels=together
 engine=finer (this is R3 Engine)
 pitch-scale=1

**Comment by cannam** [comment]
Not actually familiar with the mpv interface, but interpreting these in the most plausible-seeming ways:

_tempo=0.95_

This is `--tempo 0.95` or `-T 0.95`

_transients=mixed_
_detector=compound_
_phase=laminar_
_smoothing=off_

None of these are relevant to the R3 engine. The latter three are the defaults in any case. The first one is equivalent to `--bl-transients`.

_window=standard_

This is the default (as you might expect)

_formant=preserved_

This is `--formant` or `-F`, but it's only relevant when pitch shifting, which it appears you are not doing

_pitch=consistency_

There is no option for this in the Rubber Band command-line tool. It's relevant only when changing the pitch ratio in the middle of processing, and if you ask the command-line tool to do that (by supplying a pitch or frequency map) it will enable this option automatically.

_channels=together_

This is `--centre-focus`

_engine=finer (this is R3 Engine)_

Yep, so the `-3` option or invoke the utility as `rubberband-r3`.

_pitch-scale=1_

I assume this means no pitch shift, rather than shift by 1 of something (semitones or whatever). So no option is needed.

Putting that together, 

```
$ rubberband-r3 --tempo 0.95 --centre-focus in.wav out.wav
```

**Comment by geextahslex** [comment]
God bless you, thank you so much. That helped. R3 is really impressive, better than Cubase.
I guess mpv printed all the values for both R2 and R3, so sorry for the mess ^^

Thanks again! :)
