### ISSUE TITLE
48khz wave vs 44.1khz wave any difference? (highest quality?)

### ISSUE THREAD

**Issue by geextahslex** [breakfastquay/rubberband#107]
Hi, as I can't find any information about how this is handled by rubberband I want to know if rubberband gives a better result with a 48khz wave input instead of 44.1khz?

Also I would like to know how to get the highest quality possible?

Use case is a whole music track with vocals, melody, drums etc.

Thank you :)

**Comment by cannam** [comment]
44.1 vs 48 kHz should make no perceptible difference. The results won't be identical - the stretcher operates at the rate it is given, it doesn't resample to a single rate internally - but it is tuned and tested at both of these rates and there is no reason I am aware of why either of them would sound any better overall than the other.

With recent versions of the command-line tool, using the R3 engine with centre focus (and otherwise default settings, or perhaps with formant correction if pitch-shifting vocals) should generally give the best results. That's `rubberband -3 --centre-focus`.

**Comment by geextahslex** [comment]
Thanks for this information. `rubberband -3 --centre-focus` is also what I ended up using.
I made recently a small ranking on [reddit](https://www.reddit.com/r/audioengineering/comments/1frp5m8/timestretching_a_song_izotope_rx_vs_rubberbandr3/)
