### ISSUE TITLE
will there be any updates to rubberband?

### ISSUE THREAD

**Issue by geextahslex** [breakfastquay/rubberband#108]
Hi, as the current version 3.3.0 is over one year old I wanted to know if rubberband is still in development, or are there no plans for further improvements?

Thank you :)

**Comment by cannam** [comment]
There's been quite a lot of activity in the repo since the last release, although this round has been focused on new API rather than sound quality so if you are an end-user rather than a developer it probably won't be of much interest to you.

A release is a little overdue, but I have a few ends to tie up and have had a few too many other things calling on my time. It will be soon though!

**Comment by geextahslex** [comment]
Okay awesome news, I'm looking forward to upcoming releases :) Rubberband is really impressive.
