### ISSUE TITLE
Rubberband requiring fftw3 instead of fftw in craft

### ISSUE THREAD

**Issue by 0101coding** [breakfastquay/rubberband#25]
While installing kdenlive on macOS using craft, it pulls rubberband and it has fftw3 as a dependency in the configure file, but somehow what I have in craft is fftw 

See screenshot
<img width="875" alt="Screenshot 2020-02-18 at 16 53 13" src="https://user-images.githubusercontent.com/8036048/74752936-b2a18a00-526f-11ea-82ae-67152ce87da0.png">

**Comment by cannam** [comment]
I'm afraid I don't know what craft is, but this looks like just a naming issue. On other platforms the pkg-config file for fftw is called `fftw3.pc`, while here it appears to be called `fftw.pc`. Copying it to `fftw3.pc` might work, but this is probably an issue for the packagers.

The next Rubber Band release will have a different build system, and I'll be sure to make it check for both names - once upon a time this would have been dangerous (it might have picked up the incompatible fftw2) but I think those days are long past.

**Comment by cannam** [comment]
Predictably enough, having said I would be sure to check both names, I quite forgot to make that change before releasing v1.9.1! Doh.

However - I have also remembered that on the Mac we don't actually need fftw, since the system vDSP library suffices. And the new build system will take care of that, without failing if fftw is not found. So I think we should have got away with it, regardless of my idiocy.
