### ISSUE TITLE
Pitch quality

### ISSUE THREAD

**Issue by qo4on** [breakfastquay/rubberband#28]
Which options do I have to use to get the best possible quality when I change pitch +0.5 for a female voice audio without music? It's not clear from documentation.
```
rubberband -R -P --no-threads -p 0.5 --pitch-hq "C:\in.wav" "C:\out.wav"
```

**Comment by cannam** [comment]
The docs generally are careful not to suggest that one set of parameters will sound better than another, simply because this subject is surprisingly subjective and dependent on the material! The default options are intended to sound reasonable in most situations. You might prefer `-c 3` possibly if there are problems with spurious transient detection in a soft vocal line.
