### ISSUE TITLE
replace LADSPA plugin with LV2

### ISSUE THREAD

**Issue by Be-ing** [breakfastquay/rubberband#34]
@falkTX has made a [Rubberband LV2 plugin](https://github.com/falkTX/rubberband). It would be nice to [merge this upstream](https://github.com/falkTX/rubberband/issues/2). This could allow removing the legacy LADSPA plugin.

**Comment by cannam** [comment]
I have added an LV2 plugin. It's not the same as Filipe's, but his repo did make for useful documentation.

I didn't see a lot of point in doing this before Rubber Band v2.0, because the plugin wasn't very well-behaved previously - it is a lot more reliable now because of the timing work done for v2.0.

Even so, I'm afraid this doesn't technically fix the issue here, because the issue calls for replacing the LADSPA plugin, and I haven't done that and I don't intend to do so yet at least. That's simply because I still routinely use LADSPA hosts that don't support LV2 - indeed I develop one. The two formats are built from the same implementation at least.

**Comment by Be-ing** [comment]
Cool, thanks!

> this doesn't technically fix the issue here

:shrug: It doesn't hurt to keep the LADSPA plugin.
