### ISSUE TITLE
Rubberband 1.8.2 release status?

### ISSUE THREAD

**Issue by FadiBitar** [breakfastquay/rubberband#4]
Hi,
I see from the commit history that a version 1.8.2 is in the works, although doesn't seem to be officially released yet. Is there a timeline for 1.8.2 to be released? Is the current code considered stable?
Would appreciate your feedback!
Cheers!

**Comment by jongwook** [comment]
Also looking forward to 1.8.2 release here. I've been using Ubuntu's 1.8.1 package, but came a long way through valgrind to find out that the memory leak was due to the bugs that was fixed years ago, specifically [releasing `dblbuf` in the destructor](https://github.com/breakfastquay/rubberband/commit/7ad3bcd729a564dd0bc296adf3337331e1cbcd10#diff-6fc19519449ec0daf9d0054d99ba95ff) and [releasing `accumulator` in the destructor](https://github.com/breakfastquay/rubberband/commit/05e14a6a7d4c7d6f1f50126136dfca341a86b0e8#diff-6fc19519449ec0daf9d0054d99ba95ff).

For now, uninstalling the `librubberband2v5` package and building from the source from Github eliminated the memory leak for me.

**Comment by ryandesign** [comment]
1.8.2 was released. This issue should be closed.
