### ISSUE TITLE
Map isn't working as expected

### ISSUE THREAD

**Issue by maciejorlos** [breakfastquay/rubberband#5]
Hi,
I am trying to use rubberband with Map parameter using external file that looks like:
100 200
201 300
301 350
After applying it to
rubberband -t 1 -M ramki ruhana.wav ruhana3.wav
I get warning as follows:
ignoring mapping from chunk 0 to sample 0
ignoring mapping from chunk 0 to sample 200
WARNING: calculated output duration 0 != expected 350
ERROR: distributeRegion returned wrong duration 0, expected 350

I don't know how should I correctly create map file that will work with my wave file.
I would appreciate any help.

**Comment by cannam** [comment]
I fear this was opened at a time when I didn't have much opportunity to look at these issues, and I overlooked it. Pointless as it probably is to apologise five years later: sorry!

For posterity I think the problem is that the values in the file, which the utility reads as audio sample frame numbers (i.e. 44100 per second in typical audio), are very small and look as if they are probably intended to represent times in seconds. The stretcher is trying to figure out how to adjust stretches within regions of 50-100 samples and failing. 

I just tried this file with the current version of the utility and it didn't fail, so I suppose this logic has been made more robust at some point in the intervening time.
