### ISSUE TITLE
You have an error in docs on the main page of this git

### ISSUE THREAD

**Issue by ProgrammingLife** [breakfastquay/rubberband#58]
Here you write the example:
```
For example,
  $ rubberband -t 1.5 -p 2.0 test.wav output.wav
stretches the file test.wav to 50% longer than its original duration, shifts it up in pitch by one octave, and writes the output to output.wav.
```
but it's a pitch for one NOTE not an octave. Correct me if I'm wrong.
Tested on RubberBand 2.0.2

**Comment by cannam** [comment]
Ha, you're quite right. Amazing - it's been like that forever, I've never noticed, and you're the first person ever to point it out to me. Thank you! I've pushed a fix - I decided to keep the option as `-p 2.0` and change the description, rather than changing the option to `-f 2.0` or `-p 12.0` to match the description.
